#pragma once

void run_frame_tests();
void run_airtime_tests();
void run_duty_tests();
void run_dedup_tests();
void run_nodetable_tests();
void run_meshoverlay_tests();
void run_crypto_tests();
void run_aes_tests();
void run_sha256_tests();
void run_nec_tests();
void run_mac_tests();
void run_squeeze_tests();
void run_defrag_tests();
void run_wire3_tests();
void run_media_tests();
void run_battlog_tests();
void run_ircodes_tests();
void run_meshtastic_tests();
void run_payloads_tests();
void run_txqueue_tests();
void run_roster_tests();
void run_solar_tests();
void run_ledger_tests();
void run_rules_tests();
